### PR TITLE
Preserve parameter names

### PR DESCRIPTION
**Pull request by kaqqao**
Added `<parameters>true</parameters>` to preserve parameter names as some of the TCK currently depends on those

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Also, your test that fails because of this might be fixed with #191

**Comment by kaqqao** [comment]
Sure, this can be in TCK only, but it's entirely harmless so I added it generally.
I think there's still one failing test in current master, but have to double check and post back.
Either way, this isn't a particularly important change, I just figured it's innocuous enough not to matter. Feel free to close the PR if it's undesirable.

**Comment by phillip-kruger** [comment]
@andymc12 I think it's the same test that you fixed.

**Comment by andymc12** [comment]
@kaqqao is it test 49? 
`Expecting a Mutation with the set removed from the name, scalarHolder.`

If so, then #191 should fix it.  I think we're about ready to release 1.0.1 which includes that fix.  Let's leave this issue open until after release.  If you still have the problem after moving to version 1.0.1, then we can re-assess this PR.  Thanks!

**Comment by kaqqao** [comment]
Yes, `scalarHolder` sounds familiar, that was likely it. I'm happy with closing this.

**Comment by phillip-kruger** [comment]
Closing as discussed. Reopen if this is still an issue.

**Pull request closed without merging**
