### PR TITLE
Add testcases for @Name

### PR DESCRIPTION
**Pull request by ybroeker**
This PR adds some test cases for `@Name` on fields and methods of input-/output-types.

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Hi @ybroeker . Thanks for this. Can you maybe look at the conflicting files ? Thanks :)

**Comment by phillip-kruger** [comment]
@andymc12 please merge once you are happy.

**Comment by ybroeker** [comment]
Can fully understand your concerns, I‘m going to change this in the next few days!

Didn’t know a similar class was used somewhere else, just took this from the examples.

I could also update the spec (in a different PR), so both example and code are aligned?

**Comment by phillip-kruger** [comment]
You are awesome @ybroeker  !

**Comment by andymc12** [comment]
Agreed, many thanks @ybroeker!!

**Comment by phillip-kruger** [comment]
@andymc12 - this look ok now ? Can we merge ?

**Pull request merged**
