### PR TITLE
Removed beans.xml, as it is provided as part of each TCK test.

### LINKED ISSUE #290: beans.xml in TCK library adds beans twice
Hi, there is a `beans.xml` file in https://github.com/eclipse/microprofile-graphql/blob/master/server/tck/src/main/resources/META-INF/beans.xml

This marks the TCK library itself as a beans archive, which AFAIK is neither needed nor desired.

When you run the "container" under the same classloader as the test, this causes a duplicity of beans, as they are read both from this jar file and from the actual TCK test created through Arquillian.

Would it be possible to remove this file?

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #290

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Sorry, I merged (then reverted) then only seen you have not signed the eclipse agreement. Please reopen with agreement signed.

**Comment by phillip-kruger** [comment]
see https://github.com/eclipse/microprofile-graphql/blob/master/CONTRIBUTING.adoc

**Comment by tomas-langer** [comment]
I have signed the ECA a long time ago

**Comment by phillip-kruger** [comment]
Maybe it expired ? The check failed ?

**Pull request merged**
